### ISSUE TITLE
HANA EF Core

### ISSUE THREAD

**Issue by MMMMDCCXI** [Ralphive/cfNetDemo#1]
Hello Ralph,

I have a question regarding your blog posts with the SAP Cloud platform.
Are there already plans to support the Entity Framework Core in conjunction with HANA ? As far as I can see there is only one data provider for the normal Entity Framework 6, but a standard ASP.NET application is not possible with the SAP Cloud platform, correct ?

**Comment by achmadmulyadi** [comment]
Wow, this is one year ago, and no news regarding EF Core and Hana anywhere else. Does SAP being serious in their DB market? One of my client opted to choose Hana but with limited development options in the end. If DB meant to be open for 3rd party framework then go for it and be serious, if not, shut it and limit the options for SAP ERP only, and stop selling Hana for legacy applications.

**Comment by Ralphive** [comment]
Hi Guys, sorry but I can only comment subjects related to this code. If you want to discuss product roadmap or anything SAP related, please reach for the official channels ([SAP Community](https://www.sap.com/uk/community/topics/business-one-extensibility.html), [Customer Influence Portal](https://influence.sap.com/)). I am in no position to provide advice on this matter.

Sorry about that, but hope you guys understand.
